Improve admin services discoverability.
mozilla/partinfra-playbooks pull request #56
Opened 2016-09-21 14:39 UTC by johngian

* Setup haproxy as reverse proxy to admin services
* Use an alternative port for jenkins (was port 80)
* Backend services
** mesos
** marathon
** chronos
** jenkins
** consul
** sensu

2016-09-30 15:14 UTC, flamingspaz requested changes

2016-09-30 15:14 UTC, flamingspaz commented on roles/admin/files/haproxy.ctmpl
> +    services.mozilla.community
Let's keep our public jenkins (and other services in the future) under services.mozilla.community - we should use ops.mozilla.community instead.

2016-09-30 15:14 UTC, flamingspaz commented on roles/admin/tasks/main.yml
> +---
All of these should include the "admin" tag so we can play through the entire role

2016-09-30 15:16 UTC, flamingspaz commented
Also, change the consul.json.j2 for consul to reflect the new port

2016-10-03 09:39 UTC, flamingspaz requested changes

2016-10-03 09:39 UTC, flamingspaz commented on roles/admin/handlers/main.yml
> +    enabled: yes
Remove this line, we don't need to enable the service in the handler

2016-10-03 09:39 UTC, flamingspaz commented on roles/admin/handlers/main.yml
> +    enabled: yes
Remove this line, we don't need to enable the service in the handler

2016-10-03 09:39 UTC, flamingspaz commented on roles/jenkins/templates/consul.json.j2
> +      "http": "{{ ansible_default_ipv4['address'] }}:8081",
if we're using http checks the url needs to include `http://`. We could also use the /cc.xml endpoint so we're not pulling the entire html page each time

2016-10-03 13:14 UTC, johngian commented
test this please

2016-10-03 13:16 UTC, johngian commented
retest this please

2016-10-03 13:21 UTC, johngian commented
retest this please

2016-10-03 13:23 UTC, johngian commented
retest this please

2016-10-03 13:28 UTC, johngian commented
retest this please

2016-10-03 13:34 UTC, johngian commented
retest this please

2016-10-03 13:51 UTC, johngian commented on roles/jenkins/templates/consul.json.j2
> +      "http": "{{ ansible_default_ipv4['address'] }}:8081",
It's not much of an overhead. Let's stick with the actual check of GETting the homepage.

2016-10-03 13:51 UTC, closed without merging