Improve admin services discoverability.
mozilla/partinfra-playbooks pull request #61
Opened 2016-10-03 13:53 UTC by johngian

* Setup haproxy as reverse proxy to admin services
* Use an alternative port for jenkins (was port 80)
* Backend services
 * mesos
 * marathon
 * chronos
 * jenkins
 * uchiwa

2016-10-03 13:56 UTC, johngian commented
@flamingspaz reopened this PR updated after your comments. Also checks are now running.

2016-10-04 14:31 UTC, flamingspaz requested changes

2016-10-04 14:31 UTC, flamingspaz commented on roles/jenkins/templates/consul.json.j2
> +      "http": "{{ ansible_default_ipv4['address'] }}:8081",
This one should be http://{{ ansible_default_ipv4['address'] }}:8081

2016-10-04 15:03 UTC, flamingspaz approved these changes

2016-10-04 15:03 UTC, merged